//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCartOrder
    {
        public int ProductCartOrderID { get; set; }
        public int ProductCartID { get; set; }
        public int OrderID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ProductCart ProductCart { get; set; }
    }
}
